version: '3'

services:
  puppet:
    image: puppet/puppetserver
    hostname: puppet
    ports:
      - "8140:8140"

  node1:
    image: puppet-node
    hostname: node1
    depends_on:
      - puppet

  node2:
    image: puppet-node
    hostname: node2
    depends_on:
      - puppet